backend:
  name: github
  repo: rogue-bryan/gridsome-blog

media_folder: 'static/uploads'
public_folder: '/uploads'

collections:
  - name: 'posts'
    label: 'Post'
    folder: 'posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Page'
    folder: 'pages'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Route', name: 'route', widget: 'string' }
      - { label: 'IncludeInMenu', name: 'includeInMenu', widget: 'boolean', default: true}